### ISSUE TITLE
Support multiple listeners

### ISSUE THREAD

**Issue by lexvanderstoep** [CvanderStoep/Listener#1]
In the `TextProducer` class, only two listeners are allowed to listen.

Generalise this to support multiple listeners. Let `TextProducer` have a class variable of type `List<TextListener>`  which keeps tracks of all listeners. Of course, methods for adding/removing listeners should be added to the `TextProducer` class as well.

**Comment by CvanderStoep** [comment]
List of Textlistener added in Textproducer.java; creation of objects and adding to Listeners list done in Main.java

**Comment by CvanderStoep** [comment]
done #1
