### ISSUE TITLE
Implement a text producer which forwards data from a network port

### ISSUE THREAD

**Issue by lexvanderstoep** [CvanderStoep/Listener#6]
Implement a text producer which is attached to a given network port, and sends all the data arriving at that port to its listeners.

This producers will function in a similar manner to `TextProducer`, except that it retrieves its information from a network socket as opposed to the user input on `System.In`.

More information can be found [here](https://www.cl.cam.ac.uk/teaching/1920/FJava/workbook1.pdf).

**Comment by CvanderStoep** [comment]
First draft submitted, but at this moment you have to start the server first and then start the client. Is also just reads 1 line of text.

**Comment by CvanderStoep** [comment]
solved with the last commit. #7
